version: "3"
services:
  node-app:
    build: ./backend
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - db:/data/db
volumes:
  db:
